name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Validate AI Documentation
        run: |
          # Check that all packages with README.md also have README.ai.md
          for pkg in packages/*/README.md; do
            dir=$(dirname "$pkg")
            if [ -f "$dir/README.md" ] && [ ! -f "$dir/README.ai.md" ]; then
              echo "Missing AI documentation: $dir/README.ai.md"
              exit 1
            fi
          done

          # Validate AI documentation metadata
          for ai_doc in packages/*/README.ai.md docs/ai/*.md; do
            if [ -f "$ai_doc" ]; then
              if ! grep -q "## AI Metadata" "$ai_doc"; then
                echo "Missing AI Metadata section in: $ai_doc"
                exit 1
              fi
            fi
          done

      - name: Generate llms.txt
        run: |
          cd packages/docs-site
          pnpm llms:generate
